# Generated by Django 6.0.5 on 2026-06-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number (with country code)')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Country')),
                ('service', models.CharField(choices=[('website', 'Website Development'), ('video', 'Video Editing'), ('graphic', 'Graphic Design'), ('branding', 'Logo & Branding'), ('other', 'Other')], default='other', max_length=50)),
                ('budget', models.CharField(blank=True, choices=[('', '-- Select Budget Range --'), ('500', 'Under $500'), ('1000', '$500 - $1,000'), ('2500', '$1,000 - $2,500'), ('5000', '$2,500 - $5,000'), ('10000', '$5,000 - $10,000'), ('15000', '$10,000+'), ('flexible', 'Flexible / Not Sure')], max_length=20, verbose_name='Budget Range')),
                ('timeline', models.CharField(blank=True, choices=[('', '-- Select Timeline --'), ('asap', 'ASAP (1-2 weeks)'), ('month', 'Within a Month'), ('months', '1-3 Months'), ('flexible', 'Flexible / Not Sure')], max_length=20, verbose_name='Project Timeline')),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('website', 'Website Development'), ('video', 'Video Editing'), ('graphic', 'Graphic Design'), ('branding', 'Logo & Branding')], max_length=50)),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('project_url', models.URLField(blank=True, verbose_name='Project URL')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Portfolio Projects',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField(blank=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('icon_class', models.CharField(help_text='e.g. fa-brands fa-whatsapp, fa-solid fa-envelope', max_length=100, verbose_name='Font Awesome Icon Class')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Social Media Links',
                'ordering': ['order'],
            },
        ),
    ]
